# 2024-12-08

name: Fork & Edit Clash

on:
  workflow_dispatch:
  schedule:
    # "æ—©ä¸Š12ç‚¹ä¸ä¸­åˆ12ç‚¹è¿è¡Œ"
    - cron: "0 8,20 * * *"

jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: Amnesiash/ladder_rules_script
        path: ladder-repo

######  
    # åŠ è½½è§„åˆ™:Clash ğŸ§¸
    - name: Download Clash Rules
      run: |
        mkdir -p ladder-repo/Rules/Clash
        
        # ç›´è¿ä¿®æ­£
        curl -L -o ladder-repo/Rules/Clash/Direct+.yaml "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/UnBan.yaml"  
      
        # ä»£ç†ä¿®æ­£
        curl -L -o ladder-repo/Rules/Clash/Proxy+.yaml "https://raw.githubusercontent.com/Amnesiash/ladder_rules_script/refs/heads/main/Rules/Clash/Extra/Proxy%2B.yaml"

        # ä»£ç†åˆ—è¡¨
        curl -L -o ladder-repo/Rules/Clash/Proxy.yaml "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ProxyGFWlist.yaml"

        # ç›´è¿åˆ—è¡¨
        curl -L -o ladder-repo/Rules/Clash/Direct.yaml "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaDomain.yaml"

        # LAN
        curl -L -o ladder-repo/Rules/Clash/LAN.yaml "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/LocalAreaNetwork.yaml"
        
        # æµåª’ä½“
        curl -L -o ladder-repo/Rules/Clash/Streaming!CN.yaml "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ProxyMedia.yaml"
        curl -L -o ladder-repo/Rules/Clash/BilibiliHMT.yaml "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/BilibiliHMT.yaml"

        # è‹¹æœæœåŠ¡
        curl -L -o ladder-repo/Rules/Clash/Apple.yaml "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Apple.yaml"

        # AI
        curl -L -o ladder-repo/Rules/Clash/AI.yaml "https://raw.githubusercontent.com/Amnesiash/ladder_rules_script/refs/heads/main/Rules/Clash/Extra/AIGC.yaml"

        # GoogleCN
        curl -L -o ladder-repo/Rules/Clash/GoogleCN.yaml "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/GoogleCN.yaml" 
        
        # WeChat
        curl -L -o ladder-repo/Rules/Clash/WeChat.yaml "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Wechat.yaml"  

        # Telegram
        curl -L -o ladder-repo/Rules/Clash/Telegram.yaml "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Telegram.yaml"  

        # SteamCN
        curl -L -o ladder-repo/Rules/Clash/SteamCN.yaml "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/SteamCN.yaml" 
        
######  
    # åŠ è½½è§„åˆ™:Clash List Version ğŸ§¸
    - name: Download Clash Rules
      run: |
        mkdir -p ladder-repo/Rules/Clash/List Version
        
        # ç›´è¿ä¿®æ­£
        curl -L -o ladder-repo/Rules/Clash/List Version/Direct+.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/UnBan.list"  

        # ä»£ç†åˆ—è¡¨
        curl -L -o ladder-repo/Rules/Clash/List Version/Proxy.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyGFWlist.list"

        # ç›´è¿åˆ—è¡¨
        curl -L -o ladder-repo/Rules/Clash/List Version/Direct.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ChinaDomain.list"

        # LAN
        curl -L -o ladder-repo/Rules/Clash/List Version/LAN.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/LocalAreaNetwork.list"
        
        # æµåª’ä½“
        curl -L -o ladder-repo/Rules/Clash/List Version/Streaming!CN.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyMedia.list"
        curl -L -o ladder-repo/Rules/Clash/List Version/BilibiliHMT.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/BilibiliHMT.list"

        # è‹¹æœæœåŠ¡
        curl -L -o ladder-repo/Rules/Clash/List Version/Apple.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Apple.list"

        # GoogleCN
        curl -L -o ladder-repo/Rules/Clash/List Version/GoogleCN.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/GoogleCN.list" 
        
        # WeChat
        curl -L -o ladder-repo/Rules/Clash/List Version/WeChat.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Wechat.list"  

        # Telegram
        curl -L -o ladder-repo/Rules/Clash/List Version/Telegram.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Telegram.list"  

        # SteamCN
        curl -L -o ladder-repo/Rules/Clash/List Version/SteamCN.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/SteamCN.list" 
        
######
    - name: Add å’Œ Commits
      run: |
        cd ladder-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
